[package]
name = "iryna"
version = "0.1.5"
authors = ["archerfeel <archerfeel@gmail.com>"]
description = "A lightweight network library based on mio(work-in-progress)"
license = "MIT"

[dependencies]
mio = "0.6.12"
chashmap = "2.2.0"